cache:
  directories:
    - "node_modules"
env:
  - CODECOV_TOKEN="43368f65-01e3-434b-83cd-5d388e57f215"
language: node_js
node_js:
  - "node"
install:
  - npm ci
  - npm install codecov -g
script:
  - npm run cov
after_success:
  - codecov
  